version: '3.8'

services:
  mongodb:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - liquidation_data:/data/db

  fetcher:
    build:
      context: ./backend
      dockerfile: ./src/fetcher/Dockerfile
    ports:
      - 7701:80
    environment:
      - WALLET_SEED=${WALLET_SEED}
      - DB_USER=root
      - DB_PASSWORD=password
      - LOOP=False

  api:
    build:
      context: ./backend
      dockerfile: ./src/api/Dockerfile
    ports:
      - 7702:80
    environment:
      - WALLET_SEED=${WALLET_SEED}
      - DB_USER=root
      - DB_PASSWORD=password

  notify:
    build:
      context: ./backend
      dockerfile: ./src/notify/Dockerfile
    ports:
      - 7703:80
    environment:
      - DB_USER=root
      - DB_PASSWORD=password
    env_file:
      - dev.env

volumes:
  liquidation_data:
